import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
const dom=new JSDOM(html,{url:'http://localhost:4173/#/dashboard',pretendToBeVisual:true,runScripts:'outside-only'});
for(const key of ['window','document','navigator','localStorage','sessionStorage','location','Event','CustomEvent','FormData'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true,writable:true});
dom.window.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
dom.window.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new dom.window.Event('close'));};
dom.window.scrollBy=()=>{};
dom.window.eval(await readFile(new URL('../vendor/qrcode.js',import.meta.url),'utf8'));globalThis.qrcode=dom.window.qrcode;
let errors=[];const oldError=console.error;console.error=(...args)=>errors.push(args.join(' '));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(predicate){for(let i=0;i<100;i++){if(predicate())return;await sleep(20);}throw Error('Timed out waiting for UI: '+document.querySelector('#main')?.textContent.slice(0,250));}
const click=selector=>{const el=document.querySelector(selector);assert.ok(el,'Missing '+selector);assert.equal(el.disabled,false,'Disabled '+selector);el.click();};
const submit=id=>document.querySelector('#'+id).dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));
const navigate=async path=>{location.hash=path;await sleep(100);};
await import('../js/app.js');const api=await import('../js/services/store.js');
test('App flow: onboarding, chord transpose, setlist, live, messages and permissions',async()=>{
  await until(()=>document.querySelector('#main h1')?.textContent.includes('Tudo pronto'));
  await until(()=>document.querySelector('[data-action=skip-guide]'));
  click('[data-action=skip-guide]');assert.equal(localStorage.getItem('stage-onboarding-demo-director'),'skipped');
  await navigate('/song/horizonte');await until(()=>document.querySelector('#sheet-content .chords'));
  assert.equal(document.querySelector('#sheet-content .chords span').textContent,'G');
  click('[data-action=key-up]');await sleep(30);assert.equal(document.querySelector('#sheet-content .chords span').textContent,'G#');
  document.querySelector('#sheet-capo').value='2';document.querySelector('#sheet-capo').dispatchEvent(new Event('change',{bubbles:true}));
  assert.equal(document.querySelector('#sheet-content .chords span').textContent,'F#');
  click('[data-action=new-note]');document.querySelector('#note-form [name=text]').value='Entrada privada de teste';submit('note-form');await until(()=>document.querySelector('#notes')?.textContent.includes('Entrada privada'));
  api.setDemoUser('demo-audio');assert.equal((await api.noteList('horizonte')).some(n=>n.text==='Entrada privada de teste'),false);
  await assert.rejects(()=>api.saveSong({title:'hack',contentRaw:'C'}),/ADM MASTER/);api.setDemoUser('demo-director');
  await navigate('/setlists');click('[data-action=new-setlist]');document.querySelector('#setlist-form [name=name]').value='Repertório de teste';submit('setlist-form');await until(()=>document.querySelector('#main h1')?.textContent==='Repertório de teste');
  click('[data-action=choose-song]');click('[data-action=append-song][data-id=horizonte]');await until(()=>document.querySelector('#setlist-items')?.textContent.includes('Um novo horizonte'));
  click('[data-action=choose-song]');click('[data-action=append-song][data-id=caminho]');await until(()=>document.querySelectorAll('.setlist-item').length===2);
  click('[data-action=item-up][data-index="1"]');await until(()=>document.querySelector('.setlist-item h3')?.textContent.includes('Caminho de luz'));
  click('[data-action=start-room]');await until(()=>document.querySelector('.now h1')?.textContent==='Caminho de luz');
  const roomId=location.hash.split('/').at(-1);
  click('[data-action=live-next]');await until(()=>document.querySelector('.now h1')?.textContent==='Um novo horizonte');
  click('[data-action=live-key-up]');click('[data-action=confirmed]');await until(()=>document.querySelector('#live-notice')?.textContent.includes('Tom alterado'));
  assert.equal((await api.get('liveRooms',roomId)).items[1].key,'G#');
  click('[data-action=share-room]');assert.ok(document.querySelector('#qr svg'));assert.ok(document.querySelector('#share-url').value.includes(roomId));click('[data-action=close]');
  click('[data-action=communication]');document.querySelector('#message-form [name=text]').value='Entrar no refrão';submit('message-form');await until(()=>document.querySelector('#messages')?.textContent.includes('Entrar no refrão'));click('[data-action=close]');
  click('[data-action=live-end]');click('[data-action=confirmed]');await until(()=>document.querySelector('#live-surface')?.textContent.includes('ENCERRADA'));assert.equal((await api.get('liveRooms',roomId)).status,'ended');
  await navigate('/editor/new');await until(()=>document.querySelector('#editor-form'));const f=document.querySelector('#editor-form');f.elements.title.value='Teste & seguro';f.elements.artist.value='Autor';f.elements.contentRaw.value='[Verso]\nC  G\n<img src=x onerror=alert(1)>\nUma letra original';f.elements.contentRaw.dispatchEvent(new Event('input',{bubbles:true}));assert.equal(document.querySelector('#editor-preview img'),null);click('[data-action=publish-song]');await until(()=>document.querySelector('#main h1')?.textContent==='Teste & seguro');assert.equal(document.querySelector('#sheet-content img'),null);
  await navigate('/settings');await until(()=>document.querySelector('#demo-user'));assert.ok(document.querySelector('#main').textContent.includes('Versão instalada'));
  assert.deepEqual(errors,[]);console.error=oldError;dom.window.close();
});
